[control_plane_first]
cp1 ansible_host=159.223.50.136

[control_plane_rest]
cp2 ansible_host=188.166.191.204
cp3 ansible_host=152.42.200.227

[workers]
w1 ansible_host=159.65.139.110
w2 ansible_host=178.128.106.199

[all:vars]
ansible_user=root
container_runtime=containerd
kubernetes_version=1.34.0
control_plane_endpoint="k8s-api.mycompany.local:6443"
pod_network_cidr="10.244.0.0/16"
