apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: demo-nodejs
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  # base64 encoded "rootpassword"
  MYSQL_PASSWORD: cGFzc3dvcmQ=  # base64 encoded "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: demo-nodejs
type: Opaque
data:
  DATABASE_PASSWORD: cGFzc3dvcmQ=  # base64 encoded "password"