services:
  api:
    image: demo-go-api:1.0
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://admin:password@db:27017/?directConnection=true
    depends_on:
      db:
        condition: service_healthy
  db:
    image: demo-mongo:1.0
    build:
      context: ./mongo
      dockerfile: Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - ./data:/data/db
